### ISSUE TITLE
test error

### ISSUE THREAD

**Issue by fipoucat** [matthiasdemuzere/w2w#77]
I am testing w2w using the example given but getting an error and wonder what could be the cause:

 w2w ./sample_data lcz_zaragoza.tif geo_em.d04.nc
--> Set data, arguments and files 
> Using layer 0 of the LCZ GeoTIFF. Can be changed with -l (--lcz-band)
--> Check LCZ integrity, in terms of class labels, projection and extent
> LCZ labels as expected (1 to 17)
> LCZ provided as WGS84 (EPSG:4326)
> LCZ domain is covering WRF domain
--> Replace WRF MODIS urban LC with surrounding natural LC
Looping through urban grid pixels: 100%|██████| 263/263 [00:03<00:00, 81.43it/s]
--> Create LCZ-based geo_em file
Traceback (most recent call last):
  File "/usr/local/anaconda3/bin/w2w", line 8, in <module>
    sys.exit(main())
  File "/usr/local/anaconda3/lib/python3.8/site-packages/w2w/w2w.py", line 178, in main
    nbui_max = create_lcz_params_file(
  File "/usr/local/anaconda3/lib/python3.8/site-packages/w2w/w2w.py", line 1211, in create_lcz_params_file
    dst_data = _add_frc_lu_index_2_wrf(
  File "/usr/local/anaconda3/lib/python3.8/site-packages/w2w/w2w.py", line 1137, in _add_frc_lu_index_2_wrf
    frc_urb = _ucp_resampler(
  File "/usr/local/anaconda3/lib/python3.8/site-packages/w2w/w2w.py", line 660, in _ucp_resampler
    wrf_grid_info = _get_wrf_grid_info(info)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/w2w/w2w.py", line 603, in _get_wrf_grid_info
    'crs': wrf_proj.to_proj4(),
AttributeError: 'Proj' object has no attribute 'to_proj4'

**Comment by fipoucat** [comment]
OK, worked with a fresh env.

**Comment by theendlessriver13** [comment]
it would still be helpful for us to have the list of packages, so we could pin the version of the package, which seems to be incompatible in a lower version.

**Comment by fipoucat** [comment]
The list is too long, but find them here :
[freeze.txt](https://github.com/matthiasdemuzere/w2w/files/9149075/freeze.txt)
